# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iaInteractive' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire'
pod 'KVNProgress'
pod 'RealmSwift'
pod 'Kingfisher'

  # Pods for iaInteractive

  target 'iaInteractiveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iaInteractiveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
